version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - errname
    - errorlint
    - gochecknoinits
    - goconst
    - gocritic
    - gosec
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
  settings:
    goconst:
      ignore-tests: true
    nakedret:
      max-func-lines: 30
    nolintlint:
      allow-unused: true
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: increment-decrement
        - name: indent-error-flow
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
        - name: time-naming
        - name: unexported-return
        - name: unreachable-code
        - name: unused-parameter
        - name: var-declaration
        - name: var-naming
